-- database name house_automation
CREATE SCHEMA `house_automation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
use `house_automation`;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'automation_area_types' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'plan_types' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'plan_mappings' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'users' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'notifications' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'user_subscriptions' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'house_types' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
 SELECT CONSTRAINT_NAME as constraint_name,CONSTRAINT_NAME as constraintName,CONSTRAINT_SCHEMA as constraintSchema,CONSTRAINT_SCHEMA as constraintCatalog,TABLE_NAME as tableName,TABLE_SCHEMA as tableSchema,TABLE_SCHEMA as tableCatalog,COLUMN_NAME as columnName,REFERENCED_TABLE_SCHEMA as referencedTableSchema,REFERENCED_TABLE_SCHEMA as referencedTableCatalog,REFERENCED_TABLE_NAME as referencedTableName,REFERENCED_COLUMN_NAME as referencedColumnName FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE where TABLE_NAME = 'user_reviews' AND CONSTRAINT_NAME!='PRIMARY' AND CONSTRAINT_SCHEMA='house_automation' AND REFERENCED_TABLE_NAME IS NOT NULL;
  CREATE TABLE IF NOT EXISTS `automation_area_types` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255), `badge` VARCHAR(255), `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `automation_area_types` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `plan_types` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255), `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `plan_types` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `house_types` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255), `phone` VARCHAR(255), `email` VARCHAR(255), `city` VARCHAR(255), `message` VARCHAR(255), `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `house_types` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `plan_mappings` (`id` CHAR(36) BINARY NOT NULL , `payment_cycle` VARCHAR(255), `plan` CHAR(36) BINARY, `house_type` CHAR(36) BINARY, `area_type` CHAR(36) BINARY, `per_day_cost` INTEGER DEFAULT 0, `extra_subscription_days` INTEGER DEFAULT 0, `subscription_fee` INTEGER DEFAULT 0, `security_deposit` INTEGER DEFAULT 0, `installation_charges` INTEGER DEFAULT 0, `tax_and_other_charges` INTEGER DEFAULT 0, `offer` TINYINT(1) DEFAULT false, `pay_amount` INTEGER DEFAULT 0, `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`plan`) REFERENCES `plan_types` (`id`), FOREIGN KEY (`house_type`) REFERENCES `house_types` (`id`), FOREIGN KEY (`area_type`) REFERENCES `automation_area_types` (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `plan_mappings` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `verified_user` TINYINT(1), `name` VARCHAR(255), `user_type` ENUM('admin', 'customer'), `email` VARCHAR(255), `phone` VARCHAR(255), `password` VARCHAR(255), `address` VARCHAR(255), `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `users` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `notifications` (`id` CHAR(36) BINARY NOT NULL , `user` CHAR(36) BINARY, `type` VARCHAR(255), `message` VARCHAR(255), `title` VARCHAR(255), `redirect_url` VARCHAR(255), `read_at` DATETIME DEFAULT NULL, `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user`) REFERENCES `users` (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `notifications` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `user_subscriptions` (`id` CHAR(36) BINARY NOT NULL , `user` CHAR(36) BINARY, `plan` CHAR(36) BINARY, `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user`) REFERENCES `users` (`id`), FOREIGN KEY (`plan`) REFERENCES `plan_mappings` (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `user_subscriptions` FROM `house_automation`;
  CREATE TABLE IF NOT EXISTS `user_reviews` (`id` CHAR(36) BINARY NOT NULL , `user` CHAR(36) BINARY, `plan` CHAR(36) BINARY, `start_rate` INTEGER, `comment` VARCHAR(255), `status` VARCHAR(255) DEFAULT 'active', `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`user`) REFERENCES `users` (`id`), FOREIGN KEY (`plan`) REFERENCES `plan_mappings` (`id`)) ENGINE=InnoDB;
 SHOW INDEX FROM `user_reviews` FROM `house_automation`